"""add phone_no column nullable

Revision ID: 09c1f56165cb
Revises: 
Create Date: 2025-12-23 14:59:10.974420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c1f56165cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.String(length=15), nullable=True))
        batch_op.create_unique_constraint(None, ['phone_no'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone_no')

    # ### end Alembic commands ###
