"""add cloudinary fields

Revision ID: 571e30c51b4c
Revises: e16c9c10469e
Create Date: 2026-01-06 16:20:58.193825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571e30c51b4c'
down_revision = 'e16c9c10469e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('public_id', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('public_id')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
