"""empty message

Revision ID: 6140c6245e20
Revises: 4a279a122b74
Create Date: 2026-02-02 10:14:36.968945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6140c6245e20'
down_revision = '4a279a122b74'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_words', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale_x', sa.Float(), nullable=False, server_default="0"))
        batch_op.add_column(sa.Column('scale_y', sa.Float(), nullable=False, server_default="0"))
    # ### end Alembic commands ###

    # Optional: remove server_default if you don't want future inserts to use it
    with op.batch_alter_table('ocr_words', schema=None) as batch_op:
        batch_op.alter_column('scale_x', server_default=None)
        batch_op.alter_column('scale_y', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_words', schema=None) as batch_op:
        batch_op.drop_column('scale_y')
        batch_op.drop_column('scale_x')
    # ### end Alembic commands ###

