"""empty message

Revision ID: 811c9e9f0796
Revises: 6140c6245e20
Create Date: 2026-02-02 11:00:53.616517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811c9e9f0796'
down_revision = '6140c6245e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted to avoid NOT NULL error ###
    with op.batch_alter_table('ocr_words', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('orig_width', sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column('orig_height', sa.Integer(), nullable=False, server_default="0")
        )

    # Optional: remove server default after upgrade if not needed
    with op.batch_alter_table('ocr_words', schema=None) as batch_op:
        batch_op.alter_column('orig_width', server_default=None)
        batch_op.alter_column('orig_height', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_words', schema=None) as batch_op:
        batch_op.drop_column('orig_height')
        batch_op.drop_column('orig_width')
    # ### end Alembic commands ###
