"""Add ocr_text column to uploaded_files

Revision ID: 859e463b24b8
Revises: ab145dc4bf85
Create Date: 2026-01-09 10:39:41.325885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '859e463b24b8'
down_revision = 'ab145dc4bf85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ocr_text', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('ocr_text')

    # ### end Alembic commands ###
