"""Add FileChunk table with meta_info

Revision ID: 97f42c104f87
Revises: 
Create Date: 2026-01-16 12:54:59.693480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97f42c104f87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.DOUBLE_PRECISION()), nullable=False),
    sa.Column('meta_info', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.alter_column('ocr_text',
               existing_type=sa.TEXT(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.alter_column('ocr_text',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.drop_table('file_chunks')
    # ### end Alembic commands ###
