"""remove cloudinary columns

Revision ID: ab145dc4bf85
Revises: 571e30c51b4c
Create Date: 2026-01-07 09:39:06.783010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab145dc4bf85'
down_revision = '571e30c51b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('file_url')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
