"""Add extracted_info column to UploadedFile

Revision ID: be05d803e549
Revises: 859e463b24b8
Create Date: 2026-01-09 16:16:57.759424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be05d803e549'
down_revision = '859e463b24b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_info', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_column('extracted_info')

    # ### end Alembic commands ###
